import { Request, Response, NextFunction } from "express";
import mongoose from "mongoose";
import { Playlist, Track } from "../models";
import { getPlaylist } from "../services";

const CACHE_TTL_MS = 60 * 60 * 1000; // 1 hour

async function attachStreamUrls(playlist: any) {
  if (!playlist || !playlist.tracks || playlist.tracks.length === 0) return playlist;
  
  const trackSpotifyIds = playlist.tracks.map((t: any) => t.spotifyId);
  const readySongs = await mongoose.model("Song").find({
    spotifyTrackId: { $in: trackSpotifyIds },
    status: "ready"
  }).lean();

  const streamUrlMap = new Map(readySongs.map((s: any) => [s.spotifyTrackId, s.streamUrl]));

  return {
    ...playlist,
    tracks: playlist.tracks.map((t: any) => ({
      ...t,
      streamUrl: streamUrlMap.get(t.spotifyId) || t.streamUrl || undefined
    }))
  };
}

/**
 * GET /api/playlist/:spotifyId
 * Returns a playlist with its tracks, cache-first from MongoDB.
 */
export async function getPlaylistById(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const spotifyId = req.params.spotifyId as string;

    // Check database by spotifyId or MongoDB _id
    let playlistDoc: any = await Playlist.findOne({ spotifyId }).lean();
    if (!playlistDoc && mongoose.Types.ObjectId.isValid(spotifyId)) {
      playlistDoc = await Playlist.findById(spotifyId).lean();
    }

    if (playlistDoc) {
      if (playlistDoc.isUserCreated) {
        const trackIds = playlistDoc.tracks;
        const [tracks, songs] = await Promise.all([
          mongoose.model("Track").find({ _id: { $in: trackIds } }).lean(),
          mongoose.model("Song").find({ _id: { $in: trackIds } }).lean()
        ]);
        
        const itemMap = new Map();
        tracks.forEach((t: any) => itemMap.set(t._id.toString(), { ...t, albumArt: t.albumArt || "" }));
        songs.forEach((s: any) => itemMap.set(s._id.toString(), {
          ...s,
          spotifyId: s.spotifyTrackId || s.spotifyId || s._id.toString(),
          albumArt: s.albumArt || s.coverArt || "",
        }));

        playlistDoc.tracks = trackIds.map((id: any) => itemMap.get(id.toString())).filter(Boolean);
      } else if (playlistDoc.autoGenerated) {
        // Populate from Song collection for auto-generated playlists
        await Playlist.populate(playlistDoc, { path: "tracks", model: "Song", options: { lean: true } });
        // Normalize Song fields to Track fields expected by the frontend
        playlistDoc.tracks = playlistDoc.tracks.map((t: any) => {
          if (!t) return null;
          return {
            ...t,
            spotifyId: t.spotifyTrackId || t.spotifyId,
            albumArt: t.albumArt || t.coverArt || "",
          };
        }).filter(Boolean);
      } else {
        // Populate from Track collection for regular imported playlists
        await Playlist.populate(playlistDoc, { path: "tracks", model: "Track" });
      }

      // Return from DB immediately to avoid 500 errors. 
      // getPlaylist() currently expects a MusicBrainz UUID and will throw for Spotify IDs.
      const playlistWithStreams = await attachStreamUrls(playlistDoc);
      res.json({ success: true, source: "database", data: playlistWithStreams });
      return;
    }

    // Fetch from Spotify (NOTE: FLAG - Mismatch in service expectation)
    // The getPlaylist() function currently resolves to musicBrainzService.getPlaylist(), 
    // which expects a MusicBrainz release UUID, NOT a Spotify Playlist ID. 
    // If a cache miss occurs for an imported Spotify playlist, this will fail or throw.
    // We are deliberately leaving this as-is pending a decision on whether to 
    // re-trigger spotify-url-info scraping instead of MusicBrainz lookup.
    const spotifyPlaylist = await getPlaylist(spotifyId);

    // Upsert tracks
    const trackDocs = await Promise.all(
      spotifyPlaylist.tracks.items
        .filter((item: any) => item.track !== null)
        .map(async (item: any) => {
          const t = item.track!;
          return Track.findOneAndUpdate(
            { spotifyId: t.id },
            {
              spotifyId: t.id,
              title: t.name,
              artist: t.artists.map((a: any) => a.name).join(", "),
              album: t.album.name,
              albumArt: t.album.images?.[0]?.url || "",
              duration: t.duration_ms,
              trackNumber: t.track_number,
              previewUrl: t.preview_url || undefined,
            },
            { upsert: true, new: true, setDefaultsOnInsert: true }
          ).lean();
        })
    );

    // Upsert playlist with track references
    const savedPlaylist = await Playlist.findOneAndUpdate(
      { spotifyId },
      {
        spotifyId,
        name: spotifyPlaylist.name,
        description: spotifyPlaylist.description || "",
        coverImage: spotifyPlaylist.images?.[0]?.url || "",
        owner: spotifyPlaylist.owner?.display_name || "",
        tracks: trackDocs.map((t) => t._id),
        totalTracks: spotifyPlaylist.tracks.total,
        isPublic: spotifyPlaylist.public ?? true,
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    )
      .populate("tracks")
      .lean();

    const playlistWithStreams = await attachStreamUrls(savedPlaylist);
    res.json({ success: true, source: "spotify", data: playlistWithStreams });
  } catch (error) {
    res.status(404).json({ success: false, error: "Playlist not found" });
  }
}

/**
 * GET /api/playlist/:spotifyId/import-status
 * Returns the current import status and progress of a playlist.
 */
export async function getImportStatus(
  req: Request,
  res: Response,
  next: NextFunction
): Promise<void> {
  try {
    const spotifyId = req.params.spotifyId as string;
    
    const playlist = await Playlist.findOne({ spotifyId })
      .select("importStatus totalTracks tracks missingTracks")
      .lean();

    if (!playlist) {
      res.status(404).json({ success: false, message: "Playlist not found" });
      return;
    }

    res.json({
      success: true,
      importStatus: playlist.importStatus,
      totalTracks: playlist.totalTracks,
      tracksImportedSoFar: playlist.tracks?.length || 0,
      missingTracksCount: playlist.missingTracks?.length || 0,
      missingTracks: playlist.missingTracks || []
    });
  } catch (error) {
    next(error);
  }
}

// ==========================================
// User-Created Playlists endpoints
// ==========================================

export async function createUserPlaylist(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { name, description } = req.body;
    if (!name) {
      res.status(400).json({ success: false, error: "Name is required" });
      return;
    }

    const playlist = new Playlist({
      name,
      description: description || "",
      isUserCreated: true,
      tracks: []
    });

    await playlist.save();
    res.status(201).json({ success: true, data: playlist });
  } catch (error) {
    next(error);
  }
}

export async function getUserPlaylists(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const playlists = await Playlist.find({ isUserCreated: true }).sort({ createdAt: -1 }).lean();
    res.json({ success: true, data: playlists });
  } catch (error) {
    next(error);
  }
}

export async function addTrackToPlaylist(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = req.params;
    const { trackId } = req.body;

    if (!mongoose.Types.ObjectId.isValid(trackId)) {
      res.status(400).json({ success: false, error: "Invalid track ID" });
      return;
    }

    const playlist = await Playlist.findOne({ _id: id, isUserCreated: true });
    if (!playlist) {
      res.status(404).json({ success: false, error: "User playlist not found" });
      return;
    }

    // Convert trackId to ObjectId to use with mongoose array
    const objId = new mongoose.Types.ObjectId(trackId);

    // Push if not already present
    if (!playlist.tracks.includes(objId)) {
      playlist.tracks.push(objId);
      playlist.totalTracks = playlist.tracks.length;
      await playlist.save();
    }

    res.json({ success: true, data: playlist });
  } catch (error) {
    next(error);
  }
}

export async function removeTrackFromPlaylist(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id, trackId } = req.params;

    const playlist = await Playlist.findOne({ _id: id, isUserCreated: true });
    if (!playlist) {
      res.status(404).json({ success: false, error: "User playlist not found" });
      return;
    }

    const objId = new mongoose.Types.ObjectId(trackId as string);
    
    // Remove track
    playlist.tracks = playlist.tracks.filter(tid => !tid.equals(objId));
    playlist.totalTracks = playlist.tracks.length;
    await playlist.save();

    res.json({ success: true, data: playlist });
  } catch (error) {
    next(error);
  }
}

export async function deleteUserPlaylist(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = req.params;
    const playlist = await Playlist.findOneAndDelete({ _id: id });
    
    if (!playlist) {
      res.status(404).json({ success: false, error: "Playlist not found" });
      return;
    }

    res.json({ success: true, message: "Playlist deleted" });
  } catch (error) {
    next(error);
  }
}

export async function renameUserPlaylist(req: Request, res: Response, next: NextFunction): Promise<void> {
  try {
    const { id } = req.params;
    const { name, description } = req.body;
    
    const playlist = await Playlist.findOne({ _id: id, isUserCreated: true });
    
    if (!playlist) {
      res.status(404).json({ success: false, error: "User playlist not found" });
      return;
    }

    if (name !== undefined) playlist.name = name;
    if (description !== undefined) playlist.description = description;

    await playlist.save();
    res.json({ success: true, data: playlist });
  } catch (error) {
    next(error);
  }
}
