import { Router } from "express";
import { getPlaylistById } from "../controllers";

const router = Router();

import { Playlist } from "../models";

/** GET /api/playlist — Get all auto-generated playlists */
router.get("/", async (req, res) => {
  try {
    const playlists = await Playlist.find({ autoGenerated: true });
    res.json(playlists);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch playlists" });
  }
});

/** GET /api/playlist/:spotifyId/import-status — Import progress */
router.get("/:spotifyId/import-status", require("../controllers").getImportStatus);

/** GET /api/playlist/:spotifyId — Full playlist with tracks */
router.get("/:spotifyId", getPlaylistById);

export default router;
