import { Router } from "express";
import { getPlaylistById, createUserPlaylist, getUserPlaylists, addTrackToPlaylist, removeTrackFromPlaylist, deleteUserPlaylist, renameUserPlaylist } from "../controllers";

const router = Router();

import { Playlist } from "../models";

/** GET /api/playlist — Get all auto-generated playlists */
router.get("/", async (req, res) => {
  try {
    const playlists = await Playlist.find({ autoGenerated: true });
    res.json(playlists);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch playlists" });
  }
});

/** GET /api/playlist/:spotifyId/import-status — Import progress */
router.get("/:spotifyId/import-status", require("../controllers").getImportStatus);

// ==========================================
// User-Created Playlists
// ==========================================
router.post("/", createUserPlaylist);
router.get("/user/created", getUserPlaylists); // using /user/created to avoid collision with :spotifyId if it happens
router.post("/:id/tracks", addTrackToPlaylist);
router.delete("/:id/tracks/:trackId", removeTrackFromPlaylist);
router.delete("/:id", deleteUserPlaylist);
router.patch("/:id", renameUserPlaylist);

/** GET /api/playlist/:spotifyId — Full playlist with tracks */
router.get("/:spotifyId", getPlaylistById);

export default router;
